const types = {
  GET_MATERIALS : 'GET_MATERIALS',
  SET_MATERIALS : 'GET_MATERIALS',
  TOGGLE_FOLDER : 'TOGGLE_FOLDER',
  UPLOAD_FILES : 'UPLOAD_FILES',
  EXPAND_FOLDER : 'EXPAND_FOLDER',
  MOVE_MATERIALS : 'MOVE_MATERIALS'
  COPY_MATERIALS : 'COPY_MATERIALS',
  CLIP_MATERIALS : 'CLIP_MATERIALS',
}
